name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Branch to deploy (e.g., main, master, gh-pages)'
        required: true
        default: 'master'

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Make repository public
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
        run: |

          if [ "$priv" = "true" ]; then
             echo "Making repository public..."
              gh repo edit --repo "$REPO" --visibility public --accept-visibility-change-consequences || {
              echo "Error: Failed to make the repository public."
                exit 1
              }
          else
              echo "Repo is already public."
          fi

  deploy-pages:
    needs: make-public
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Debug workspace 
        run: | 
         echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" 
         pwd ls -la find . -maxdepth 3 -name package.json -print
      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}

      - name: Build site
        run: npm run build

      - name: Check if artifact exists
        run: |
         if [ ! -f "/home/runner/work/_temp/artifact.tar" ]; then
         echo "artifact.tar does not exist!"
         exit 1
         fi
      - name: Upload Pages artifact (repo root)
        uses: actions/upload-pages-artifact@v3
        with:
          path: /home/runner/work/_temp/artifact.tar
          # Exclusions can be handled by a .gitignore-style file if needed
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: /home/runner/work/_temp/artifact.tar
          

      - name: Show files to deploy
        run: ls -la dist

      # Upload the build output to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          # If your build output is in a folder other than ./public, set it here
          # For example, if output is in 'dist', use 'dist'
          folder: public
